'use client';

import { useState, useEffect } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { useTheme } from '@/contexts/ThemeContext';
import { makeAuthenticatedRequest } from '@/utils/api';
import { ApiResponse } from '@/types';
import { RoleGuard } from '@/components/RoleGuard';

interface Invoice {
  invoice_id: number;
  invoice_number: string;
  store_id: number;
  billing_month: string;
  base_amount: number;
  sms_charges: number;
  push_notification_charges: number;
  additional_charges: number;
  total_amount: number;
  total_sms_sent: number;
  total_notifications_sent: number;
  payment_status: 'pending' | 'paid' | 'overdue' | 'cancelled';
  payment_date: string | null;
  payment_method: string | null;
  payment_reference: string | null;
  due_date: string;
  issued_date: string;
  created_at: string;
}

export default function BillingPage() {
  const { user } = useAuth();
  const { theme } = useTheme();
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedInvoice, setSelectedInvoice] = useState<Invoice | null>(null);

  const isDark = theme === 'dark';

  useEffect(() => {
    if (user?.store_id) {
      fetchInvoices();
    }
  }, [user]);

  const fetchInvoices = async () => {
    try {
      setLoading(true);
      setError(null);
      const response: ApiResponse<Invoice[]> = await makeAuthenticatedRequest(
        `/billing?store_id=${user?.store_id}`,
        {},
        true,
        user?.store_id,
        user?.branch_id || undefined
      );

      if (response.success) {
        const invoicesData = Array.isArray(response.data)
          ? response.data
          : response.data?.data || [];
        setInvoices(invoicesData);
      } else {
        setError(response.message || 'Failed to fetch invoices');
      }
    } catch (err: any) {
      console.error('Error fetching invoices:', err);
      setError(err.message || 'Failed to load invoices');
    } finally {
      setLoading(false);
    }
  };

  const getStatusBadge = (status: string) => {
    const statusClasses = {
      paid: isDark ? 'bg-green-900 text-green-200' : 'bg-green-100 text-green-800',
      pending: isDark ? 'bg-yellow-900 text-yellow-200' : 'bg-yellow-100 text-yellow-800',
      overdue: isDark ? 'bg-red-900 text-red-200' : 'bg-red-100 text-red-800',
      cancelled: isDark ? 'bg-gray-800 text-gray-300' : 'bg-gray-100 text-gray-800',
    };
    return statusClasses[status as keyof typeof statusClasses] || statusClasses.pending;
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
    }).format(amount);
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    });
  };

  if (loading) {
    return (
      <RoleGuard requiredPermissions={['view_reports']}>
        <div className={`min-h-screen flex items-center justify-center ${isDark ? 'bg-gray-900' : 'bg-gray-50'}`}>
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
        </div>
      </RoleGuard>
    );
  }

  return (
    <RoleGuard requiredPermissions={['view_reports']}>
      <div className={`min-h-screen ${isDark ? 'bg-gray-900' : 'bg-gray-50'}`}>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="mb-6">
            <h1 className={`text-3xl font-bold ${isDark ? 'text-white' : 'text-gray-900'}`}>
              Billing & Invoices
            </h1>
            <p className={`mt-2 ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>
              View your monthly invoices and payment history
            </p>
          </div>

          {error && (
            <div className={`mb-6 p-4 rounded-lg ${isDark ? 'bg-red-900 border border-red-700' : 'bg-red-50 border border-red-200'}`}>
              <p className={isDark ? 'text-red-200' : 'text-red-700'}>{error}</p>
            </div>
          )}

          {invoices.length === 0 ? (
            <div className={`rounded-lg shadow p-8 text-center ${isDark ? 'bg-gray-800' : 'bg-white'}`}>
              <p className={isDark ? 'text-gray-400' : 'text-gray-600'}>
                No invoices found. Invoices will appear here once generated by the super admin.
              </p>
            </div>
          ) : (
            <div className={`rounded-lg shadow overflow-hidden ${isDark ? 'bg-gray-800' : 'bg-white'}`}>
              <div className="overflow-x-auto">
                <table className="min-w-full divide-y divide-gray-200">
                  <thead className={isDark ? 'bg-gray-700' : 'bg-gray-50'}>
                    <tr>
                      <th className={`px-6 py-3 text-left text-xs font-medium uppercase tracking-wider ${isDark ? 'text-gray-300' : 'text-gray-500'}`}>
                        Invoice Number
                      </th>
                      <th className={`px-6 py-3 text-left text-xs font-medium uppercase tracking-wider ${isDark ? 'text-gray-300' : 'text-gray-500'}`}>
                        Billing Month
                      </th>
                      <th className={`px-6 py-3 text-left text-xs font-medium uppercase tracking-wider ${isDark ? 'text-gray-300' : 'text-gray-500'}`}>
                        SMS Count
                      </th>
                      <th className={`px-6 py-3 text-left text-xs font-medium uppercase tracking-wider ${isDark ? 'text-gray-300' : 'text-gray-500'}`}>
                        Notifications
                      </th>
                      <th className={`px-6 py-3 text-left text-xs font-medium uppercase tracking-wider ${isDark ? 'text-gray-300' : 'text-gray-500'}`}>
                        Total Amount
                      </th>
                      <th className={`px-6 py-3 text-left text-xs font-medium uppercase tracking-wider ${isDark ? 'text-gray-300' : 'text-gray-500'}`}>
                        Payment Status
                      </th>
                      <th className={`px-6 py-3 text-left text-xs font-medium uppercase tracking-wider ${isDark ? 'text-gray-300' : 'text-gray-500'}`}>
                        Due Date
                      </th>
                      <th className={`px-6 py-3 text-left text-xs font-medium uppercase tracking-wider ${isDark ? 'text-gray-300' : 'text-gray-500'}`}>
                        Actions
                      </th>
                    </tr>
                  </thead>
                  <tbody className={`divide-y ${isDark ? 'divide-gray-700 bg-gray-800' : 'divide-gray-200 bg-white'}`}>
                    {invoices.map((invoice) => (
                      <tr key={invoice.invoice_id} className={isDark ? 'hover:bg-gray-700' : 'hover:bg-gray-50'}>
                        <td className={`px-6 py-4 whitespace-nowrap ${isDark ? 'text-white' : 'text-gray-900'}`}>
                          {invoice.invoice_number}
                        </td>
                        <td className={`px-6 py-4 whitespace-nowrap ${isDark ? 'text-gray-300' : 'text-gray-500'}`}>
                          {formatDate(invoice.billing_month)}
                        </td>
                        <td className={`px-6 py-4 whitespace-nowrap ${isDark ? 'text-gray-300' : 'text-gray-500'}`}>
                          {invoice.total_sms_sent || 0}
                        </td>
                        <td className={`px-6 py-4 whitespace-nowrap ${isDark ? 'text-gray-300' : 'text-gray-500'}`}>
                          {invoice.total_notifications_sent || 0}
                        </td>
                        <td className={`px-6 py-4 whitespace-nowrap font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>
                          {formatCurrency(invoice.total_amount)}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap">
                          <span className={`px-2 py-1 text-xs rounded-full ${getStatusBadge(invoice.payment_status)}`}>
                            {invoice.payment_status.charAt(0).toUpperCase() + invoice.payment_status.slice(1)}
                          </span>
                        </td>
                        <td className={`px-6 py-4 whitespace-nowrap ${isDark ? 'text-gray-300' : 'text-gray-500'}`}>
                          {formatDate(invoice.due_date)}
                        </td>
                        <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                          <button
                            onClick={() => setSelectedInvoice(invoice)}
                            className={`${isDark ? 'text-blue-400 hover:text-blue-300' : 'text-blue-600 hover:text-blue-900'}`}
                          >
                            View Details
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}

          {selectedInvoice && (
            <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
              <div className={`max-w-2xl w-full rounded-lg shadow-xl ${isDark ? 'bg-gray-800' : 'bg-white'} p-6 max-h-[90vh] overflow-y-auto`}>
                <div className="flex justify-between items-center mb-4">
                  <h2 className={`text-2xl font-bold ${isDark ? 'text-white' : 'text-gray-900'}`}>
                    Invoice Details
                  </h2>
                  <button
                    onClick={() => setSelectedInvoice(null)}
                    className={`text-2xl ${isDark ? 'text-gray-400 hover:text-gray-300' : 'text-gray-500 hover:text-gray-700'}`}
                  >
                    ×
                  </button>
                </div>

                <div className="space-y-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <p className={`text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Invoice Number</p>
                      <p className={`font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>{selectedInvoice.invoice_number}</p>
                    </div>
                    <div>
                      <p className={`text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Billing Month</p>
                      <p className={`font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>{formatDate(selectedInvoice.billing_month)}</p>
                    </div>
                    <div>
                      <p className={`text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Base Amount</p>
                      <p className={`font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>{formatCurrency(selectedInvoice.base_amount)}</p>
                    </div>
                    <div>
                      <p className={`text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>SMS Charges</p>
                      <p className={`font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>{formatCurrency(selectedInvoice.sms_charges)}</p>
                    </div>
                    <div>
                      <p className={`text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Push Notification Charges</p>
                      <p className={`font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>{formatCurrency(selectedInvoice.push_notification_charges)}</p>
                    </div>
                    <div>
                      <p className={`text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Additional Charges</p>
                      <p className={`font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>{formatCurrency(selectedInvoice.additional_charges)}</p>
                    </div>
                    <div>
                      <p className={`text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Total Amount</p>
                      <p className={`text-xl font-bold ${isDark ? 'text-white' : 'text-gray-900'}`}>{formatCurrency(selectedInvoice.total_amount)}</p>
                    </div>
                    <div>
                      <p className={`text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Payment Status</p>
                      <span className={`px-2 py-1 text-xs rounded-full ${getStatusBadge(selectedInvoice.payment_status)}`}>
                        {selectedInvoice.payment_status.charAt(0).toUpperCase() + selectedInvoice.payment_status.slice(1)}
                      </span>
                    </div>
                    {selectedInvoice.payment_date && (
                      <div>
                        <p className={`text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Payment Date</p>
                        <p className={`font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>{formatDate(selectedInvoice.payment_date)}</p>
                      </div>
                    )}
                    {selectedInvoice.payment_method && (
                      <div>
                        <p className={`text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Payment Method</p>
                        <p className={`font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>{selectedInvoice.payment_method}</p>
                      </div>
                    )}
                    {selectedInvoice.payment_reference && (
                      <div>
                        <p className={`text-sm ${isDark ? 'text-gray-400' : 'text-gray-600'}`}>Payment Reference</p>
                        <p className={`font-semibold ${isDark ? 'text-white' : 'text-gray-900'}`}>{selectedInvoice.payment_reference}</p>
                      </div>
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </RoleGuard>
  );
}
